# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'projectios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectios

  target 'projectiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectiosUITests' do
    # Pods for testing
  end
  
  pod 'SwiftMessageBar', '~> 5.6.1'

end
